options(stringsAsFactors=FALSE,warn=1,digits=17)
suppressPackageStartupMessages({library(data.table);library(jsonlite);library(digest)})
setDTthreads(1L)
source('code/00_setup/paths.R');out<-private_output('sicdb_clinical')
started<-Sys.time();dir.create(file.path(out,'restricted_work'),showWarnings=FALSE)
src<-release_path('sicdb_clinical_input')
before<-digest(file=src,algo='sha256');d<-fread(src)
stopifnot(nrow(d)==2044,uniqueN(d$CaseID)==2044,uniqueN(d$PatientID)==1996)
gates<-rbindlist(lapply(c('restart_binary','death_72h_binary','composite_restart_or_death'),function(k)data.table(endpoint=k,cases=nrow(d),known=sum(!is.na(d[[k]])),positive=sum(d[[k]]==1,na.rm=TRUE),unknown=sum(is.na(d[[k]])))))
fwrite(gates,file.path(out,'S1_endpoint_gate_check.csv'))
stopifnot(all(d$first_time_hours>=4&d$first_time_hours<=72),!anyNA(d$first_time_hours),all(d$cif_evaluable),all(d$recorded_crrt_active_pre6h%in%c(0,1)),all(d$recorded_crrt_active_pre6h==d$predictor_rrt_t0_recorded))
vars<-c('predictor_age','predictor_female','predictor_episode_peak_nee','predictor_last_positive_nee','predictor_positive_nee_hours','predictor_multivaso_peak','predictor_sofa_24h','predictor_mechanical_ventilation_t0','recorded_crrt_active_pre6h','predictor_mean_map_4h','predictor_map_source_invasive','predictor_mean_heart_rate_4h','predictor_urine_output_24h_ml')
labels<-c('Age (years; grouped source values)','Female sex','Episode peak NEE (micrograms/kg/min)','Last positive NEE (micrograms/kg/min)','Cumulative positive NEE exposure (h)','At least two vasopressors at peak NEE','SOFA before withdrawal (mature daily proxy)','Mechanical ventilation at withdrawal (airway/device proxy)','Recorded CRRT activity in preceding 6 h','Mean MAP in preceding 4 h (mmHg)','Invasive MAP source','Mean heart rate in preceding 4 h (beats/min)','Urine output in preceding 24 h (mL)')
notes<-c('Source age is grouped; no continuous age reconstruction.','Source sex mapping retained.','Original conversion and four-decimal NEE arithmetic retained.','Original last positive interval value.','Original episode definition and exposure arithmetic retained.','Original simultaneous-drug indicator at peak.','Latest daily SOFA label whose 24 h window matured by t0, within preceding 24 h; not reconstructed instantaneous SOFA.','Airway interval and mechanical signals; insufficient or conflicting evidence remains UNKNOWN.','No recent activity recorded is coded 0 by the existing recorded-activity definition, not clinical absence of all RRT.','Complete pre-t0 hourly bins; invasive MAP preferred when available.','Invasive versus noninvasive source under original measurement rule.','Complete pre-t0 hourly bins with original signal priority.','Sum of available hourly urine bins; missing coverage is not imputed.')
binary<-c(2,6,8,9,11);z<-d[!is.na(restart_binary)]
base<-rbindlist(lapply(seq_along(vars),function(i){k<-vars[i];rbindlist(lapply(0:1,function(y){x<-z[restart_binary==y][[k]];ok<-x[!is.na(x)];qs<-if(length(ok)&&!(i%in%binary))quantile(ok,c(.25,.5,.75),type=7,names=FALSE)else rep(NA_real_,3);data.table(variable=k,label=labels[i],group=if(y==1)'Restart within 72 h'else'No restart within 72 h',group_cases=length(x),available_n=length(ok),missing_n=sum(is.na(x)),missing_percent=100*mean(is.na(x)),q1=qs[1],median=qs[2],q3=qs[3],positive_n=if(i%in%binary)sum(ok==1)else NA_integer_,positive_percent=if(i%in%binary)100*mean(ok==1)else NA_real_,grouped_population_missing_n=sum(is.na(z[[k]])),grouped_population_n=nrow(z),grouped_population_missing_percent=100*mean(is.na(z[[k]])),all2044_missing_n=sum(is.na(d[[k]])),measurement_note=notes[i])}))}))
fwrite(base,file.path(out,'S1_baseline_by_restart_EN.csv'))
md<-c('# Characteristics at vasopressor withdrawal by subsequent restart','', sprintf('| Characteristic | No restart (n = %s) | Restart (n = %s) | Missing, n (%%) |',format(sum(z$restart_binary==0),big.mark=','),format(sum(z$restart_binary==1),big.mark=',')),'|---|---:|---:|---:|')
for(i in seq_along(vars)){b<-base[variable==vars[i]];cell<-function(y){a<-b[group==y];if(a$available_n==0)return('Unavailable');if(i%in%binary)sprintf('%d (%.2f%%); available n = %d',a$positive_n,a$positive_percent,a$available_n)else sprintf('%.2f [%.2f, %.2f]; n = %d',a$median,a$q1,a$q3,a$available_n)};md<-c(md,paste('|',labels[i],'|',cell('No restart within 72 h'),'|',cell('Restart within 72 h'),'|',sprintf('%d (%.2f%%)',b$grouped_population_missing_n[1],b$grouped_population_missing_percent[1]),'|'))}
md<-c(md,'','Continuous values are median [Q1, Q3] and available n. Binary percentages use the nonmissing denominator. Missingness is before imputation, among restart-evaluable cases. Cases with unknown restart status are described separately. No group tests were performed.','',paste0('- ',labels,': ',notes))
writeLines(md,file.path(out,'S1_baseline_by_restart_EN.md'),useBytes=TRUE)
outcome_row<-function(label,x,total=length(x),family='nonexclusive_outcome'){n<-sum(x==1,na.rm=TRUE);N<-sum(!is.na(x));data.table(outcome=label,positive_n=n,evaluable_n=N,eligible_n=total,unknown_n=sum(is.na(x)),proportion=if(N)n/N else NA_real_,category_family=family)}
rows<-list()
for(h in c(12,24,48,72)){v<-if(h==72)d$restart_binary else rep(NA_real_,nrow(d));if(h!=72){v[d$restart_binary==0 & !is.na(d$restart_binary)]<-0;ii<-which(d$restart_binary==1);v[ii]<-as.integer(d$restart_hours[ii]<=h);ii<-which(is.na(d$restart_binary)&(d$coverage_end-d$t0)/3600>=h);v[ii]<-0};rows[[length(rows)+1L]]<-outcome_row(paste0('Same-case restart within ',h,' h'),v)}
rows[[5]]<-outcome_row('All-cause death within 72 h',d$death_72h_binary)
rows[[6]]<-outcome_row('Restart or all-cause death within 72 h',d$composite_restart_or_death)
dead<-d[death_72h_binary==1];stopifnot(nrow(dead)==80,!anyNA(dead$death))
no_prior<-as.integer(is.na(dead$valid_restart_time)|dead$valid_restart_time>=dead$death)
rows[[7]]<-outcome_row('Deaths without preceding valid restart among 72 h deaths',no_prior,family='death_subset')
states<-c(RESTART='First event: restart',DEATH='First event: death before restart',NORMAL_CARE_END='First event: normal case end',ADMIN_HORIZON='No first event by 72 h',CARE_END_UNCLASSIFIED='First observation end: type unclassified')
stopifnot(all(d$cif_state%in%names(states)))
for(s in names(states))rows[[length(rows)+1L]]<-outcome_row(states[s],as.integer(d$cif_state==s),family='mutually_exclusive_first_event')
tab<-rbindlist(rows);fwrite(tab,file.path(out,'S1_outcomes_table2_column.csv'))
rt<-d[restart_binary==1];stopifnot(nrow(rt)==684,!anyNA(rt$restart_hours),all(rt$restart_hours>=4 & rt$restart_hours<=72))
qs<-quantile(rt$restart_hours,c(.25,.5,.75),names=FALSE,type=7)
fwrite(data.table(cases=nrow(rt),patients=uniqueN(rt$PatientID),origin='original cessation t0',unit='hours',minimum=min(rt$restart_hours),q1=qs[1],median=qs[2],q3=qs[3],maximum=max(rt$restart_hours)),file.path(out,'S1_restart_time_among_restarted.csv'))
after<-digest(file=src,algo='sha256');stopifnot(before==after)
fwrite(data.table(path=src,before=before,after=after,unchanged=TRUE),file.path(out,'S1_source_hash_check.csv'))
capture.output(sessionInfo(),file=file.path(out,'S1_R_session_info.txt'))
write_json(list(status='PASS_PENDING_INDEPENDENT_REVIEW',cases=2044,patients=1996,restarts=684,baseline_cases=sum(!is.na(d$restart_binary)),unknown_restart=sum(is.na(d$restart_binary)),model_fits=0,imputations=0,source_unchanged=TRUE,elapsed_seconds=as.numeric(difftime(Sys.time(),started,units='secs'))),file.path(out,'S1_QC.json'),auto_unbox=TRUE,pretty=TRUE)
print(tab);print(qs)
